name: Create tag on new DNS Proxy version

on:
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00

jobs:
  createtag:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl and jq
        run: sudo apt update && sudo apt install -y curl jq
      - name: Get latest DNS Proxy tag
        run: echo "TAG_NAME=$(curl https://api.github.com/repos/AdguardTeam/dnsproxy/releases/latest | jq -r '.tag_name')" >> $GITHUB_ENV
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Create tag and push
        run: git tag $TAG_NAME 2> /dev/null && git push --tags || echo "No new version published"
